version: "3"

services:
  api:
    build: ./app
    container_name: fastapi-ml
    environment:
      - MODEL_PATH=/opt/app/sklearn_model/lr_model.joblib
    ports:
      - "8000:8000"
    networks:
      - network

networks:
    network: {}